### PR TITLE
fix #2350 

### LINKED ISSUE #2350: Android Invalid method call when use Dart >= 3.8
**Describe the bug**
When you try to make a card payment in the sample: using "simple-Using weebhook" menu option, Android returns an error:

======== Exception caught by services library ======================================================
The following FormatException was thrown during a platform message callback:
Invalid method call

When the exception was thrown, this was the stack:
#0 StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:612:7)
https://github.com/flutter-stripe/flutter_stripe/pull/1 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:605:35)
https://github.com/flutter-stripe/flutter_stripe/pull/2 MethodChannel.setMethodCallHandler. (package:flutter/src/services/platform_channel.dart:597:55)
https://github.com/flutter-stripe/flutter_stripe/pull/3 _DefaultBinaryMessenger.setMessageHandler. (package:flutter/src/services/binding.dart:663:35)
https://github.com/flutter-stripe/flutter_stripe/pull/4 _invoke2 (dart:ui/hooks.dart:388:13)
https://github.com/flutter-stripe/flutter_stripe/pull/5 _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
https://github.com/flutter-stripe/flutter_stripe/pull/6 _Channel.push (dart:ui/channel_buffers.dart:136:31)
https://github.com/flutter-stripe/flutter_stripe/pull/7 ChannelBuffers.push (dart:ui/channel_buffers.dart:344:17)

Image

**To Reproduce**
1. run the sample version flutter_stripe 12.3.0.
2. Tapping the "Simple - Using webhooks" menu option.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

```
======== Exception caught by services library ======================================================
The following FormatException was thrown during a platform message callback:
Invalid method call

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:612:7)
#1      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:605:35)
#2      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:597:55)
#3      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:663:35)
#4      _invoke2 (dart:ui/hooks.dart:388:13)
#5      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#6      _Channel.push (dart:ui/channel_buffers.dart:136:31)
#7      ChannelBuffers.push (dart:ui/channel_buffers.dart:344:17)
#8      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:819:22)
#9      _dispatchPlatformMessage (dart:ui/hooks.dart:302:31)
====================================================================================================

```
**Expected behavior**
Not error must happen.

**Smartphone / tablet**
Device: [emulator ]
OS: [ Android 15 x86_64]
Package version: [12.3.0]
Flutter 3.41.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90673a4eef (3 days ago) • 2026-02-18 13:54:59 -0800
Engine • hash d96704abcce17ff165bbef9d77123407ef961017 (revision 6c0baaebf7) (3 days ago) • 2026-02-18 19:22:23.000Z
Tools • Dart 3.11.0 • DevTools 2.54.1

**Additional context**
in the same machine if we use the **Flutter_stripe: 11.5.0** there is not errors, The issue start from version 12.0.0 on Dart version 3.8 or above

### PR DESCRIPTION
**Pull request by remonh87**
make sure that writable map returns the correct size from the underlying set

## Summary by CodeRabbit

* **Improvements**
  * Broader card network support in the payment screen—no longer restricts accepted card brands.
  * Improved internal map/size handling for Android payment operations, enhancing data reliability.

### CODE REVIEW

File: packages/stripe_android/android/src/main/kotlin/com/facebook/react/bridge/WritableMap.java [hunk 1]
```diff
@@ -16,6 +16,21 @@ public WritableMap() {
...
     }
 
+    /**
+     * WritableMap stores its data in the inherited HashMap via put(), not in the JSONObject field.
+     * ReadableMap.size() checks the JSONObject (always 0 for WritableMap), so we must override
+     * it here to check the HashMap, which is where our data actually lives.
+     */
+    @Override
+    public int size() {
+        return entrySet().size();
```
Comment (jonasbark) [inline packages/stripe_android/android/src/main/kotlin/com/facebook/react/bridge/WritableMap.java]: this method is correctly overriden in the ReadableMap already - it might make sense to add the isEmpty method to ReadableMap, though
