### PR TITLE
 feat: web fixes and features

### LINKED ISSUE #541: CardField text color hard-coded on Web
The field itself matches my app theme, but the text color seems hard-coded to black irrespective of applied TextStyle.

image

### LINKED ISSUE #1208: Stripe Web Billing details country
**Describe the bug**
When you add a new card in web Stripe response this error 
`StripeError(type: invalid_request_error, code: parameter_invalid_empty, decline_code: null, message: You passed an empty string for 'payment_method_data[billing_details][address][country]'. We assume empty values are an attempt to unset a parameter; however 'payment_method_data[billing_details][address][country]' cannot be unset. You should remove 'payment_method_data[billing_details][address][country]' from your request or supply a non-empty value., param: payment_method_data[billing_details][address][country])`
This error not is showed in mobile (Android or iOS)

What is the reason for country is required in web but in mobile not?

The model BillingDetails Address have all parameters as optional but country is required when use this. 

**To Reproduce**
1. Entering number 4111 1111 1111 1111 into the cardfield and all dates
2. Add city and address one, in billing details not include country.
```
final _bill = BillingDetails(
      address: Address(
        line1: "TEST",
        city: "Test",
      ),
      name: "Test Card",
      email: "email_test@test.com",
    );
final payment = PaymentMethodParams.card(
        paymentMethodData: PaymentMethodData(billingDetails: _bill),
      );
      final response = await Stripe.instance.createPaymentMethod(
          params: payment,
          options: PaymentMethodOptions(setupFutureUsage: setUpForFutureUsage));
      await Stripe.instance.confirmSetupIntent(
          paymentIntentClientSecret: clientSecret,
          params: payment,
          options: PaymentMethodOptions(setupFutureUsage: setUpForFutureUsage));
```
4. Card is saved in mobile but in web show error

**Expected behavior**
Web and mobile must be works as same parameters or include in model 'country' as required

**Smartphone / tablet**
 - Web

**Additional context**
This is happen in web with the last version
  flutter_stripe: ^9.1.1
  flutter_stripe_web: ^4.0.1

### LINKED ISSUE #1212: PaymentMethod model card
**Describe the bug**
When add a payment method in Flutter Web, PaymentMethod model have last4 and other dates null

This is print model with .toJson() method
```
paymentMethod.toJson()
 = 
{
  id: pm_1MzMZXKZL4P2bq5WB33lrCaL,
  livemode: false,
  paymentMethodType: card,
  billingDetails: {
    email: null,
    address: null,
    phone: null,
    name: null
  },
  Card: {
    brand: visa,
    country: US,
    expYear: null,
    expMonth: null,
    funding: credit,
    last4: null,
    preferredNetwork: null,
    availableNetworks: null
  },
  SepaDebit: {
    country: null,
    bankCode: null,
    fingerprint: null,
    last4: null
  },
  BacsDebit: {
    sortCode: null,
    fingerprint: null,
    last4: null
  },
  AuBecsDebit: {
    fingerprint: null,
    last4: null,
    bsbNumber: null
  },
  Sofort: {
    country: null
  },
  Ideal: {
    bankIdentifierCode: null,
    bank: null
  },
  Fpx: {
    bank: null,
    accountHolderType: null
  },
  Upi: {
    vpa: null
  },
  USBankAccount: {
    routingNumber: null,
    last4: null,
    accountHolderType: Unknown,
    accountType: Unknown,
    bankName: null,
    fingerprint: null,
    linkedAccount: null,
    preferredNetworks: null,
    supportedNetworks: null
  },
  customerId: null
}
```

Card json

```
{
  brand: visa,
  country: US,
  expYear: null,
  expMonth: null,
  funding: credit,
  last4: null,
  preferredNetwork: null,
  availableNetworks: null
}
```
Response paymentMethod is 
https://api.stripe.com/v1/payment_methods

```
{
  "id": "pm_1MzMZXKZL4P2bq5Wv88au8qe",
  "object": "payment_method",
  "billing_details": {
    "address": {
      "city": null,
      "country": null,
      "line1": null,
      "line2": null,
      "postal_code": null,
      "state": null
    },
    "email": null,
    "name": null,
    "phone": null
  },
  "card": {
    "brand": "visa",
    "checks": {
      "address_line1_check": null,
      "address_postal_code_check": null,
      "cvc_check": null
    },
    "country": "US",
    "exp_month": 12,
    "exp_year": 2023,
    "funding": "credit",
    "generated_from": null,
    "last4": "1111",
    "networks": {
      "available": [
        "visa"
      ],
      "preferred": null
    },
    "three_d_secure_usage": {
      "supported": true
    },
    "wallet": null
  },
  "created": 1682093551,
  "customer": null,
  "livemode": false,
  "type": "card"
}
```
Notice that response contains information about
"country": "US",
    "exp_month": 12,
    "exp_year": 2023,
    "funding": "credit",
    "generated_from": null,
    "last4": "1111",

But in model PaymentMethod this is not present

**To Reproduce**
1. Add new card in flutter web

**Expected behavior**
Card values is null

**Smartphone / tablet**
 - Flutter web - Chrome browser

### LINKED ISSUE #1260: Be able to change payment element layout option
We ought to be able to change this layout parameter, and not hardcoded to accordion like it is here.

https://github.com/flutter-stripe/flutter_stripe/blob/9a31e1d8889bd531a1e96572aedf40a568fa7fc0/packages/stripe_web/lib/src/widgets/payment_element.dart#L156

### PR DESCRIPTION
**Pull request by jamesblasco**
- Makes a singleton for WebStripe. Accesible by WebStripe.instance
- Allows to change the layout for the payment element. Closes #1260 
- Allows to change the full appearance for the payment element. It is possible to fully customise it by adding any of the values from [the appearance api](https://stripe.com/docs/elements/appearance-api)
- Fixes parsing PaymentMethod to contain dates and last4 digits. Closes #1212
- Fixes parsing Address to not add empty strings if null. Closes #1208
- Adds support for confirmAcssDebitPayment on web  `WebStripe.instance.confirmAcssDebitPayment`. Ref #794 
- Fixes text color not sync with CardStyle on the web card field. Closes #541 
- Adds independent method for `confirmIdealPayment`: `WebStripe.instance.confirmIdealPayment`, that allows to pass a custom returnUrl. Ref #1075

### CODE REVIEW

File: packages/stripe_web/lib/src/parser/payment_intent.dart [hunk 1]
```diff
@@ -136,23 +136,23 @@ extension BillingDetailsToJs on BillingDetails {
 extension ShippingAddressFromJs on Address {
   js.BillingAddress toBillingAddressJs() {
     return js.BillingAddress(
-      city: city ?? '',
-      country: country ?? '',
-      line1: line1 ?? '',
-      line2: line2 ?? '',
-      postalCode: postalCode ?? '',
-      state: state ?? '',
+      city: city,
```
Comment (remonh87) [inline packages/stripe_web/lib/src/parser/payment_intent.dart:139]: 👍

File: packages/stripe_web/lib/src/web_stripe.dart [hunk 2]
```diff
@@ -64,27 +69,28 @@ class WebStripe extends StripePlatform {
...
-        return createCardPaymentMethod(data, {});
-    }
-
-    throw UnimplementedError();
+    return data.maybeWhen(
+      card: (data) {
+        return _createCardPaymentMethod(data);
+      },
+      orElse: () {
+        throw UnimplementedError();
```
Comment (remonh87) [inline packages/stripe_web/lib/src/web_stripe.dart:77]: Shouldn't we throw a `WebUnsupportedError` here?

File: packages/stripe_web/lib/src/web_stripe.dart [hunk 3]
```diff
@@ -175,6 +181,51 @@ class WebStripe extends StripePlatform {
...
+        paymentMethod: stripe_js.IdealPaymentMethodDetails.withBank(
+          ideal: stripe_js.IdealBankData(bank: paymentData.bankName!),
+        ),
+        returnUrl: returnUrl ?? urlScheme,
+      ),
+    );
+
+    if (response.error != null) {
+      throw StripeError(
+        message: response.error?.message ?? '',
```
Comment (remonh87) [inline packages/stripe_web/lib/src/web_stripe.dart:201]: I think we can use `!` here since you already checked if it is null.

File: packages/stripe_web/lib/src/web_stripe.dart [hunk 4]
```diff
@@ -175,6 +181,51 @@ class WebStripe extends StripePlatform {
     return response.paymentIntent!.parse();
   }
 
+  Future<PaymentIntent> confirmIdealPayment(
+      String paymentIntentClientSecret, PaymentMethodDataIdeal paymentData,
+      {String? returnUrl}) async {
+    if (paymentData.bankName == null) throw 'bankName is required for web';
```
Comment (remonh87) [inline packages/stripe_web/lib/src/web_stripe.dart:187]: I think it is better to call bankName is required for idea. since this is not specific to web

**Review by remonh87 — APPROVED** [review]
left a few minor comments

**Comment by rignaneseleo** [comment]
Does this allow payments on web?
