### PR TITLE
fix: upgrade to android agp 8

### LINKED ISSUE #1469: Not building with AGP 8
**Describe the bug**
Unable to build.

Execution failed for task ':stripe_android:compileDebugKotlin'.
```
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

**To Reproduce**
Try to run an app with:
```
kotlin: 1.8.22
Android Gradle Plugin version 8.1.2
Gradle Wrapper: distributionUrl=https\://services.gradle.org/distributions/gradle-8.1-all.zip
```

**Expected behavior**
The build to complete

**Smartphone / tablet**
 - Pixel 6 Emulator
 - OS: Android 13
 - Package version: 9.5.0+1
 - Flutter version : 3.13

**Additional context**
No change when setting compile option or kotlin option to whatever. Also following the Gradle documentation with toolchains and all this complicated stuff did not help;

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
 }
```

### PR DESCRIPTION
**Pull request by remonh87**
Fix #1469

### CODE REVIEW

File: packages/stripe_checkout/lib/src/platforms/stripe_checkout.dart [hunk 1]
```diff
@@ -8,51 +8,6 @@ import 'package:webview_flutter/webview_flutter.dart';
...
-        canceledUrl: canceledUrl!,
-      ),
-    ),
-  );
-  return response ?? const CheckoutResponse.canceled();
-}
-
 /// Prebuilt payment web page hosted on Stripe loaded
 /// in app via a webview
 class CheckoutPage extends StatefulWidget {
```
Comment (remonh87) [inline packages/stripe_checkout/lib/src/platforms/stripe_checkout.dart:13]: maybe we should discontinue checkout
